#!/bin/sh

for t in 1 2 3 4 # ... and the rest of your test files
do
	echo === Test $t ===
	./bst < tests/$t.in > tests/$t.observed 2>&1

	if diff -Z tests/$t.exp tests/$t.observed > /dev/null 2>&1
	then
		echo "Passed"
	else
		echo "Failed - check differences between tests/$t.expected and tests/$t.observed"
	fi
done