#!/usr/bin/python3

import psycopg2

try:
	db = psycopg2.connect("dbname=uni")
	cur = db.cursor()
	cur.execute("select code,name from Subjects order by code")
	for tup in cur.fetchall():
		print(tup)
	db.close()

except Exception as err:
	print(err)
	exit(1)
