# DO NOT CHANGE THIS FILE!
#
# This is run on a non-standard gitlab runner so any changes you make may break in unexpected ways.
# If you feel for some reason this file MUST be changed, please post on the course forum so it can
# be discussed between you and course staff.
#
image: comp1531/basic:20T3

stages:
  - checks

pytest:
  stage: checks
  script:
    # Generate coverage data at the same time we run the tests
    - coverage run -m pytest
    - coverage report
  coverage: '/primes.py.*\s+(\d+%)$/'

pylint:
  stage: checks
  script:
    - pylint *.py
